/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authEntrarRouteImport } from './routes/(auth)/entrar'
import { Route as authCadastroRouteImport } from './routes/(auth)/cadastro'
import { Route as appAppRouteImport } from './routes/(app)/_app'
import { Route as appAppIndexRouteImport } from './routes/(app)/_app.index'
import { Route as appAppContatoRouteImport } from './routes/(app)/_app.contato'
import { Route as appAppBuscarRouteImport } from './routes/(app)/_app.buscar'
import { Route as appAppPacoteNomeRouteImport } from './routes/(app)/_app.pacote.$nome'
import { Route as appAppcheckoutCheckoutRouteImport } from './routes/(app)/_app/(checkout)/checkout'
import { Route as appAppadministracaoAdministracaoRouteImport } from './routes/(app)/_app/(administracao)/administracao'
import { Route as appAppadministracaoAdministracaoDashboardRouteImport } from './routes/(app)/_app/(administracao)/administracao.dashboard'
import { Route as appAppusuarioUsuarioViagemListarRouteImport } from './routes/(app)/_app/(usuario)/$usuario.viagem.listar'
import { Route as appAppcheckoutCheckoutConfirmacaoCompraIdRouteImport } from './routes/(app)/_app/(checkout)/checkout_.confirmacao.$compraId'
import { Route as appAppadministracaoAdministracaoUsuarioListarRouteImport } from './routes/(app)/_app/(administracao)/administracao.usuario.listar'
import { Route as appAppadministracaoAdministracaoTransporteRegistrarRouteImport } from './routes/(app)/_app/(administracao)/administracao.transporte.registrar'
import { Route as appAppadministracaoAdministracaoTransporteListarRouteImport } from './routes/(app)/_app/(administracao)/administracao.transporte.listar'
import { Route as appAppadministracaoAdministracaoPacotedefotoRegistrarRouteImport } from './routes/(app)/_app/(administracao)/administracao.pacotedefoto.registrar'
import { Route as appAppadministracaoAdministracaoPacotedefotoListarRouteImport } from './routes/(app)/_app/(administracao)/administracao.pacotedefoto.listar'
import { Route as appAppadministracaoAdministracaoPacoteRegistrarRouteImport } from './routes/(app)/_app/(administracao)/administracao.pacote.registrar'
import { Route as appAppadministracaoAdministracaoPacoteListarRouteImport } from './routes/(app)/_app/(administracao)/administracao.pacote.listar'
import { Route as appAppadministracaoAdministracaoHotelRegistrarRouteImport } from './routes/(app)/_app/(administracao)/administracao.hotel.registrar'
import { Route as appAppadministracaoAdministracaoHotelListarRouteImport } from './routes/(app)/_app/(administracao)/administracao.hotel.listar'
import { Route as appAppusuarioUsuarioViagemListarIdRouteImport } from './routes/(app)/_app/(usuario)/$usuario_.viagem.listar.$id'

const authEntrarRoute = authEntrarRouteImport.update({
  id: '/(auth)/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const authCadastroRoute = authCadastroRouteImport.update({
  id: '/(auth)/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const appAppRoute = appAppRouteImport.update({
  id: '/(app)/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const appAppIndexRoute = appAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appAppRoute,
} as any)
const appAppContatoRoute = appAppContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => appAppRoute,
} as any)
const appAppBuscarRoute = appAppBuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => appAppRoute,
} as any)
const appAppPacoteNomeRoute = appAppPacoteNomeRouteImport.update({
  id: '/pacote/$nome',
  path: '/pacote/$nome',
  getParentRoute: () => appAppRoute,
} as any)
const appAppcheckoutCheckoutRoute = appAppcheckoutCheckoutRouteImport.update({
  id: '/(checkout)/checkout',
  path: '/checkout',
  getParentRoute: () => appAppRoute,
} as any)
const appAppadministracaoAdministracaoRoute =
  appAppadministracaoAdministracaoRouteImport.update({
    id: '/(administracao)/administracao',
    path: '/administracao',
    getParentRoute: () => appAppRoute,
  } as any)
const appAppadministracaoAdministracaoDashboardRoute =
  appAppadministracaoAdministracaoDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => appAppadministracaoAdministracaoRoute,
  } as any)
const appAppusuarioUsuarioViagemListarRoute =
  appAppusuarioUsuarioViagemListarRouteImport.update({
    id: '/(usuario)/$usuario/viagem/listar',
    path: '/$usuario/viagem/listar',
    getParentRoute: () => appAppRoute,
  } as any)
const appAppcheckoutCheckoutConfirmacaoCompraIdRoute =
  appAppcheckoutCheckoutConfirmacaoCompraIdRouteImport.update({
    id: '/(checkout)/checkout_/confirmacao/$compraId',
    path: '/checkout/confirmacao/$compraId',
    getParentRoute: () => appAppRoute,
  } as any)
const appAppadministracaoAdministracaoUsuarioListarRoute =
  appAppadministracaoAdministracaoUsuarioListarRouteImport.update({
    id: '/usuario/listar',
    path: '/usuario/listar',
    getParentRoute: () => appAppadministracaoAdministracaoRoute,
  } as any)
const appAppadministracaoAdministracaoTransporteRegistrarRoute =
  appAppadministracaoAdministracaoTransporteRegistrarRouteImport.update({
    id: '/transporte/registrar',
    path: '/transporte/registrar',
    getParentRoute: () => appAppadministracaoAdministracaoRoute,
  } as any)
const appAppadministracaoAdministracaoTransporteListarRoute =
  appAppadministracaoAdministracaoTransporteListarRouteImport.update({
    id: '/transporte/listar',
    path: '/transporte/listar',
    getParentRoute: () => appAppadministracaoAdministracaoRoute,
  } as any)
const appAppadministracaoAdministracaoPacotedefotoRegistrarRoute =
  appAppadministracaoAdministracaoPacotedefotoRegistrarRouteImport.update({
    id: '/pacotedefoto/registrar',
    path: '/pacotedefoto/registrar',
    getParentRoute: () => appAppadministracaoAdministracaoRoute,
  } as any)
const appAppadministracaoAdministracaoPacotedefotoListarRoute =
  appAppadministracaoAdministracaoPacotedefotoListarRouteImport.update({
    id: '/pacotedefoto/listar',
    path: '/pacotedefoto/listar',
    getParentRoute: () => appAppadministracaoAdministracaoRoute,
  } as any)
const appAppadministracaoAdministracaoPacoteRegistrarRoute =
  appAppadministracaoAdministracaoPacoteRegistrarRouteImport.update({
    id: '/pacote/registrar',
    path: '/pacote/registrar',
    getParentRoute: () => appAppadministracaoAdministracaoRoute,
  } as any)
const appAppadministracaoAdministracaoPacoteListarRoute =
  appAppadministracaoAdministracaoPacoteListarRouteImport.update({
    id: '/pacote/listar',
    path: '/pacote/listar',
    getParentRoute: () => appAppadministracaoAdministracaoRoute,
  } as any)
const appAppadministracaoAdministracaoHotelRegistrarRoute =
  appAppadministracaoAdministracaoHotelRegistrarRouteImport.update({
    id: '/hotel/registrar',
    path: '/hotel/registrar',
    getParentRoute: () => appAppadministracaoAdministracaoRoute,
  } as any)
const appAppadministracaoAdministracaoHotelListarRoute =
  appAppadministracaoAdministracaoHotelListarRouteImport.update({
    id: '/hotel/listar',
    path: '/hotel/listar',
    getParentRoute: () => appAppadministracaoAdministracaoRoute,
  } as any)
const appAppusuarioUsuarioViagemListarIdRoute =
  appAppusuarioUsuarioViagemListarIdRouteImport.update({
    id: '/(usuario)/$usuario_/viagem/listar/$id',
    path: '/$usuario/viagem/listar/$id',
    getParentRoute: () => appAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/cadastro': typeof authCadastroRoute
  '/entrar': typeof authEntrarRoute
  '/buscar': typeof appAppBuscarRoute
  '/contato': typeof appAppContatoRoute
  '/': typeof appAppIndexRoute
  '/administracao': typeof appAppadministracaoAdministracaoRouteWithChildren
  '/checkout': typeof appAppcheckoutCheckoutRoute
  '/pacote/$nome': typeof appAppPacoteNomeRoute
  '/administracao/dashboard': typeof appAppadministracaoAdministracaoDashboardRoute
  '/administracao/hotel/listar': typeof appAppadministracaoAdministracaoHotelListarRoute
  '/administracao/hotel/registrar': typeof appAppadministracaoAdministracaoHotelRegistrarRoute
  '/administracao/pacote/listar': typeof appAppadministracaoAdministracaoPacoteListarRoute
  '/administracao/pacote/registrar': typeof appAppadministracaoAdministracaoPacoteRegistrarRoute
  '/administracao/pacotedefoto/listar': typeof appAppadministracaoAdministracaoPacotedefotoListarRoute
  '/administracao/pacotedefoto/registrar': typeof appAppadministracaoAdministracaoPacotedefotoRegistrarRoute
  '/administracao/transporte/listar': typeof appAppadministracaoAdministracaoTransporteListarRoute
  '/administracao/transporte/registrar': typeof appAppadministracaoAdministracaoTransporteRegistrarRoute
  '/administracao/usuario/listar': typeof appAppadministracaoAdministracaoUsuarioListarRoute
  '/checkout/confirmacao/$compraId': typeof appAppcheckoutCheckoutConfirmacaoCompraIdRoute
  '/$usuario/viagem/listar': typeof appAppusuarioUsuarioViagemListarRoute
  '/$usuario/viagem/listar/$id': typeof appAppusuarioUsuarioViagemListarIdRoute
}
export interface FileRoutesByTo {
  '/cadastro': typeof authCadastroRoute
  '/entrar': typeof authEntrarRoute
  '/buscar': typeof appAppBuscarRoute
  '/contato': typeof appAppContatoRoute
  '/': typeof appAppIndexRoute
  '/administracao': typeof appAppadministracaoAdministracaoRouteWithChildren
  '/checkout': typeof appAppcheckoutCheckoutRoute
  '/pacote/$nome': typeof appAppPacoteNomeRoute
  '/administracao/dashboard': typeof appAppadministracaoAdministracaoDashboardRoute
  '/administracao/hotel/listar': typeof appAppadministracaoAdministracaoHotelListarRoute
  '/administracao/hotel/registrar': typeof appAppadministracaoAdministracaoHotelRegistrarRoute
  '/administracao/pacote/listar': typeof appAppadministracaoAdministracaoPacoteListarRoute
  '/administracao/pacote/registrar': typeof appAppadministracaoAdministracaoPacoteRegistrarRoute
  '/administracao/pacotedefoto/listar': typeof appAppadministracaoAdministracaoPacotedefotoListarRoute
  '/administracao/pacotedefoto/registrar': typeof appAppadministracaoAdministracaoPacotedefotoRegistrarRoute
  '/administracao/transporte/listar': typeof appAppadministracaoAdministracaoTransporteListarRoute
  '/administracao/transporte/registrar': typeof appAppadministracaoAdministracaoTransporteRegistrarRoute
  '/administracao/usuario/listar': typeof appAppadministracaoAdministracaoUsuarioListarRoute
  '/checkout/confirmacao/$compraId': typeof appAppcheckoutCheckoutConfirmacaoCompraIdRoute
  '/$usuario/viagem/listar': typeof appAppusuarioUsuarioViagemListarRoute
  '/$usuario/viagem/listar/$id': typeof appAppusuarioUsuarioViagemListarIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)/_app': typeof appAppRouteWithChildren
  '/(auth)/cadastro': typeof authCadastroRoute
  '/(auth)/entrar': typeof authEntrarRoute
  '/(app)/_app/buscar': typeof appAppBuscarRoute
  '/(app)/_app/contato': typeof appAppContatoRoute
  '/(app)/_app/': typeof appAppIndexRoute
  '/(app)/_app/(administracao)/administracao': typeof appAppadministracaoAdministracaoRouteWithChildren
  '/(app)/_app/(checkout)/checkout': typeof appAppcheckoutCheckoutRoute
  '/(app)/_app/pacote/$nome': typeof appAppPacoteNomeRoute
  '/(app)/_app/(administracao)/administracao/dashboard': typeof appAppadministracaoAdministracaoDashboardRoute
  '/(app)/_app/(administracao)/administracao/hotel/listar': typeof appAppadministracaoAdministracaoHotelListarRoute
  '/(app)/_app/(administracao)/administracao/hotel/registrar': typeof appAppadministracaoAdministracaoHotelRegistrarRoute
  '/(app)/_app/(administracao)/administracao/pacote/listar': typeof appAppadministracaoAdministracaoPacoteListarRoute
  '/(app)/_app/(administracao)/administracao/pacote/registrar': typeof appAppadministracaoAdministracaoPacoteRegistrarRoute
  '/(app)/_app/(administracao)/administracao/pacotedefoto/listar': typeof appAppadministracaoAdministracaoPacotedefotoListarRoute
  '/(app)/_app/(administracao)/administracao/pacotedefoto/registrar': typeof appAppadministracaoAdministracaoPacotedefotoRegistrarRoute
  '/(app)/_app/(administracao)/administracao/transporte/listar': typeof appAppadministracaoAdministracaoTransporteListarRoute
  '/(app)/_app/(administracao)/administracao/transporte/registrar': typeof appAppadministracaoAdministracaoTransporteRegistrarRoute
  '/(app)/_app/(administracao)/administracao/usuario/listar': typeof appAppadministracaoAdministracaoUsuarioListarRoute
  '/(app)/_app/(checkout)/checkout_/confirmacao/$compraId': typeof appAppcheckoutCheckoutConfirmacaoCompraIdRoute
  '/(app)/_app/(usuario)/$usuario/viagem/listar': typeof appAppusuarioUsuarioViagemListarRoute
  '/(app)/_app/(usuario)/$usuario_/viagem/listar/$id': typeof appAppusuarioUsuarioViagemListarIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/cadastro'
    | '/entrar'
    | '/buscar'
    | '/contato'
    | '/'
    | '/administracao'
    | '/checkout'
    | '/pacote/$nome'
    | '/administracao/dashboard'
    | '/administracao/hotel/listar'
    | '/administracao/hotel/registrar'
    | '/administracao/pacote/listar'
    | '/administracao/pacote/registrar'
    | '/administracao/pacotedefoto/listar'
    | '/administracao/pacotedefoto/registrar'
    | '/administracao/transporte/listar'
    | '/administracao/transporte/registrar'
    | '/administracao/usuario/listar'
    | '/checkout/confirmacao/$compraId'
    | '/$usuario/viagem/listar'
    | '/$usuario/viagem/listar/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/cadastro'
    | '/entrar'
    | '/buscar'
    | '/contato'
    | '/'
    | '/administracao'
    | '/checkout'
    | '/pacote/$nome'
    | '/administracao/dashboard'
    | '/administracao/hotel/listar'
    | '/administracao/hotel/registrar'
    | '/administracao/pacote/listar'
    | '/administracao/pacote/registrar'
    | '/administracao/pacotedefoto/listar'
    | '/administracao/pacotedefoto/registrar'
    | '/administracao/transporte/listar'
    | '/administracao/transporte/registrar'
    | '/administracao/usuario/listar'
    | '/checkout/confirmacao/$compraId'
    | '/$usuario/viagem/listar'
    | '/$usuario/viagem/listar/$id'
  id:
    | '__root__'
    | '/(app)/_app'
    | '/(auth)/cadastro'
    | '/(auth)/entrar'
    | '/(app)/_app/buscar'
    | '/(app)/_app/contato'
    | '/(app)/_app/'
    | '/(app)/_app/(administracao)/administracao'
    | '/(app)/_app/(checkout)/checkout'
    | '/(app)/_app/pacote/$nome'
    | '/(app)/_app/(administracao)/administracao/dashboard'
    | '/(app)/_app/(administracao)/administracao/hotel/listar'
    | '/(app)/_app/(administracao)/administracao/hotel/registrar'
    | '/(app)/_app/(administracao)/administracao/pacote/listar'
    | '/(app)/_app/(administracao)/administracao/pacote/registrar'
    | '/(app)/_app/(administracao)/administracao/pacotedefoto/listar'
    | '/(app)/_app/(administracao)/administracao/pacotedefoto/registrar'
    | '/(app)/_app/(administracao)/administracao/transporte/listar'
    | '/(app)/_app/(administracao)/administracao/transporte/registrar'
    | '/(app)/_app/(administracao)/administracao/usuario/listar'
    | '/(app)/_app/(checkout)/checkout_/confirmacao/$compraId'
    | '/(app)/_app/(usuario)/$usuario/viagem/listar'
    | '/(app)/_app/(usuario)/$usuario_/viagem/listar/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appAppRoute: typeof appAppRouteWithChildren
  authCadastroRoute: typeof authCadastroRoute
  authEntrarRoute: typeof authEntrarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)/entrar': {
      id: '/(auth)/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof authEntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/cadastro': {
      id: '/(auth)/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof authCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_app': {
      id: '/(app)/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_app/': {
      id: '/(app)/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appAppIndexRouteImport
      parentRoute: typeof appAppRoute
    }
    '/(app)/_app/contato': {
      id: '/(app)/_app/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof appAppContatoRouteImport
      parentRoute: typeof appAppRoute
    }
    '/(app)/_app/buscar': {
      id: '/(app)/_app/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof appAppBuscarRouteImport
      parentRoute: typeof appAppRoute
    }
    '/(app)/_app/pacote/$nome': {
      id: '/(app)/_app/pacote/$nome'
      path: '/pacote/$nome'
      fullPath: '/pacote/$nome'
      preLoaderRoute: typeof appAppPacoteNomeRouteImport
      parentRoute: typeof appAppRoute
    }
    '/(app)/_app/(checkout)/checkout': {
      id: '/(app)/_app/(checkout)/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof appAppcheckoutCheckoutRouteImport
      parentRoute: typeof appAppRoute
    }
    '/(app)/_app/(administracao)/administracao': {
      id: '/(app)/_app/(administracao)/administracao'
      path: '/administracao'
      fullPath: '/administracao'
      preLoaderRoute: typeof appAppadministracaoAdministracaoRouteImport
      parentRoute: typeof appAppRoute
    }
    '/(app)/_app/(administracao)/administracao/dashboard': {
      id: '/(app)/_app/(administracao)/administracao/dashboard'
      path: '/dashboard'
      fullPath: '/administracao/dashboard'
      preLoaderRoute: typeof appAppadministracaoAdministracaoDashboardRouteImport
      parentRoute: typeof appAppadministracaoAdministracaoRoute
    }
    '/(app)/_app/(usuario)/$usuario/viagem/listar': {
      id: '/(app)/_app/(usuario)/$usuario/viagem/listar'
      path: '/$usuario/viagem/listar'
      fullPath: '/$usuario/viagem/listar'
      preLoaderRoute: typeof appAppusuarioUsuarioViagemListarRouteImport
      parentRoute: typeof appAppRoute
    }
    '/(app)/_app/(checkout)/checkout_/confirmacao/$compraId': {
      id: '/(app)/_app/(checkout)/checkout_/confirmacao/$compraId'
      path: '/checkout/confirmacao/$compraId'
      fullPath: '/checkout/confirmacao/$compraId'
      preLoaderRoute: typeof appAppcheckoutCheckoutConfirmacaoCompraIdRouteImport
      parentRoute: typeof appAppRoute
    }
    '/(app)/_app/(administracao)/administracao/usuario/listar': {
      id: '/(app)/_app/(administracao)/administracao/usuario/listar'
      path: '/usuario/listar'
      fullPath: '/administracao/usuario/listar'
      preLoaderRoute: typeof appAppadministracaoAdministracaoUsuarioListarRouteImport
      parentRoute: typeof appAppadministracaoAdministracaoRoute
    }
    '/(app)/_app/(administracao)/administracao/transporte/registrar': {
      id: '/(app)/_app/(administracao)/administracao/transporte/registrar'
      path: '/transporte/registrar'
      fullPath: '/administracao/transporte/registrar'
      preLoaderRoute: typeof appAppadministracaoAdministracaoTransporteRegistrarRouteImport
      parentRoute: typeof appAppadministracaoAdministracaoRoute
    }
    '/(app)/_app/(administracao)/administracao/transporte/listar': {
      id: '/(app)/_app/(administracao)/administracao/transporte/listar'
      path: '/transporte/listar'
      fullPath: '/administracao/transporte/listar'
      preLoaderRoute: typeof appAppadministracaoAdministracaoTransporteListarRouteImport
      parentRoute: typeof appAppadministracaoAdministracaoRoute
    }
    '/(app)/_app/(administracao)/administracao/pacotedefoto/registrar': {
      id: '/(app)/_app/(administracao)/administracao/pacotedefoto/registrar'
      path: '/pacotedefoto/registrar'
      fullPath: '/administracao/pacotedefoto/registrar'
      preLoaderRoute: typeof appAppadministracaoAdministracaoPacotedefotoRegistrarRouteImport
      parentRoute: typeof appAppadministracaoAdministracaoRoute
    }
    '/(app)/_app/(administracao)/administracao/pacotedefoto/listar': {
      id: '/(app)/_app/(administracao)/administracao/pacotedefoto/listar'
      path: '/pacotedefoto/listar'
      fullPath: '/administracao/pacotedefoto/listar'
      preLoaderRoute: typeof appAppadministracaoAdministracaoPacotedefotoListarRouteImport
      parentRoute: typeof appAppadministracaoAdministracaoRoute
    }
    '/(app)/_app/(administracao)/administracao/pacote/registrar': {
      id: '/(app)/_app/(administracao)/administracao/pacote/registrar'
      path: '/pacote/registrar'
      fullPath: '/administracao/pacote/registrar'
      preLoaderRoute: typeof appAppadministracaoAdministracaoPacoteRegistrarRouteImport
      parentRoute: typeof appAppadministracaoAdministracaoRoute
    }
    '/(app)/_app/(administracao)/administracao/pacote/listar': {
      id: '/(app)/_app/(administracao)/administracao/pacote/listar'
      path: '/pacote/listar'
      fullPath: '/administracao/pacote/listar'
      preLoaderRoute: typeof appAppadministracaoAdministracaoPacoteListarRouteImport
      parentRoute: typeof appAppadministracaoAdministracaoRoute
    }
    '/(app)/_app/(administracao)/administracao/hotel/registrar': {
      id: '/(app)/_app/(administracao)/administracao/hotel/registrar'
      path: '/hotel/registrar'
      fullPath: '/administracao/hotel/registrar'
      preLoaderRoute: typeof appAppadministracaoAdministracaoHotelRegistrarRouteImport
      parentRoute: typeof appAppadministracaoAdministracaoRoute
    }
    '/(app)/_app/(administracao)/administracao/hotel/listar': {
      id: '/(app)/_app/(administracao)/administracao/hotel/listar'
      path: '/hotel/listar'
      fullPath: '/administracao/hotel/listar'
      preLoaderRoute: typeof appAppadministracaoAdministracaoHotelListarRouteImport
      parentRoute: typeof appAppadministracaoAdministracaoRoute
    }
    '/(app)/_app/(usuario)/$usuario_/viagem/listar/$id': {
      id: '/(app)/_app/(usuario)/$usuario_/viagem/listar/$id'
      path: '/$usuario/viagem/listar/$id'
      fullPath: '/$usuario/viagem/listar/$id'
      preLoaderRoute: typeof appAppusuarioUsuarioViagemListarIdRouteImport
      parentRoute: typeof appAppRoute
    }
  }
}

interface appAppadministracaoAdministracaoRouteChildren {
  appAppadministracaoAdministracaoDashboardRoute: typeof appAppadministracaoAdministracaoDashboardRoute
  appAppadministracaoAdministracaoHotelListarRoute: typeof appAppadministracaoAdministracaoHotelListarRoute
  appAppadministracaoAdministracaoHotelRegistrarRoute: typeof appAppadministracaoAdministracaoHotelRegistrarRoute
  appAppadministracaoAdministracaoPacoteListarRoute: typeof appAppadministracaoAdministracaoPacoteListarRoute
  appAppadministracaoAdministracaoPacoteRegistrarRoute: typeof appAppadministracaoAdministracaoPacoteRegistrarRoute
  appAppadministracaoAdministracaoPacotedefotoListarRoute: typeof appAppadministracaoAdministracaoPacotedefotoListarRoute
  appAppadministracaoAdministracaoPacotedefotoRegistrarRoute: typeof appAppadministracaoAdministracaoPacotedefotoRegistrarRoute
  appAppadministracaoAdministracaoTransporteListarRoute: typeof appAppadministracaoAdministracaoTransporteListarRoute
  appAppadministracaoAdministracaoTransporteRegistrarRoute: typeof appAppadministracaoAdministracaoTransporteRegistrarRoute
  appAppadministracaoAdministracaoUsuarioListarRoute: typeof appAppadministracaoAdministracaoUsuarioListarRoute
}

const appAppadministracaoAdministracaoRouteChildren: appAppadministracaoAdministracaoRouteChildren =
  {
    appAppadministracaoAdministracaoDashboardRoute:
      appAppadministracaoAdministracaoDashboardRoute,
    appAppadministracaoAdministracaoHotelListarRoute:
      appAppadministracaoAdministracaoHotelListarRoute,
    appAppadministracaoAdministracaoHotelRegistrarRoute:
      appAppadministracaoAdministracaoHotelRegistrarRoute,
    appAppadministracaoAdministracaoPacoteListarRoute:
      appAppadministracaoAdministracaoPacoteListarRoute,
    appAppadministracaoAdministracaoPacoteRegistrarRoute:
      appAppadministracaoAdministracaoPacoteRegistrarRoute,
    appAppadministracaoAdministracaoPacotedefotoListarRoute:
      appAppadministracaoAdministracaoPacotedefotoListarRoute,
    appAppadministracaoAdministracaoPacotedefotoRegistrarRoute:
      appAppadministracaoAdministracaoPacotedefotoRegistrarRoute,
    appAppadministracaoAdministracaoTransporteListarRoute:
      appAppadministracaoAdministracaoTransporteListarRoute,
    appAppadministracaoAdministracaoTransporteRegistrarRoute:
      appAppadministracaoAdministracaoTransporteRegistrarRoute,
    appAppadministracaoAdministracaoUsuarioListarRoute:
      appAppadministracaoAdministracaoUsuarioListarRoute,
  }

const appAppadministracaoAdministracaoRouteWithChildren =
  appAppadministracaoAdministracaoRoute._addFileChildren(
    appAppadministracaoAdministracaoRouteChildren,
  )

interface appAppRouteChildren {
  appAppBuscarRoute: typeof appAppBuscarRoute
  appAppContatoRoute: typeof appAppContatoRoute
  appAppIndexRoute: typeof appAppIndexRoute
  appAppadministracaoAdministracaoRoute: typeof appAppadministracaoAdministracaoRouteWithChildren
  appAppcheckoutCheckoutRoute: typeof appAppcheckoutCheckoutRoute
  appAppPacoteNomeRoute: typeof appAppPacoteNomeRoute
  appAppcheckoutCheckoutConfirmacaoCompraIdRoute: typeof appAppcheckoutCheckoutConfirmacaoCompraIdRoute
  appAppusuarioUsuarioViagemListarRoute: typeof appAppusuarioUsuarioViagemListarRoute
  appAppusuarioUsuarioViagemListarIdRoute: typeof appAppusuarioUsuarioViagemListarIdRoute
}

const appAppRouteChildren: appAppRouteChildren = {
  appAppBuscarRoute: appAppBuscarRoute,
  appAppContatoRoute: appAppContatoRoute,
  appAppIndexRoute: appAppIndexRoute,
  appAppadministracaoAdministracaoRoute:
    appAppadministracaoAdministracaoRouteWithChildren,
  appAppcheckoutCheckoutRoute: appAppcheckoutCheckoutRoute,
  appAppPacoteNomeRoute: appAppPacoteNomeRoute,
  appAppcheckoutCheckoutConfirmacaoCompraIdRoute:
    appAppcheckoutCheckoutConfirmacaoCompraIdRoute,
  appAppusuarioUsuarioViagemListarRoute: appAppusuarioUsuarioViagemListarRoute,
  appAppusuarioUsuarioViagemListarIdRoute:
    appAppusuarioUsuarioViagemListarIdRoute,
}

const appAppRouteWithChildren =
  appAppRoute._addFileChildren(appAppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  appAppRoute: appAppRouteWithChildren,
  authCadastroRoute: authCadastroRoute,
  authEntrarRoute: authEntrarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
